name: Automerge dependabot updates

on: pull_request_review_comment

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: auto-merge
        uses: darthtrevino/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY  }}
